### ISSUE TITLE
关于方向

### ISSUE THREAD

**Issue by JJOGGER** [NateRobinson/CardStackViewpager#1]
您是怎么将他原本下拉翻页的效果改成上拉翻页的？

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by NateRobinson** [comment]
Viewpager的setPageTransformer(boolean reverseDrawingOrder, ViewPager.PageTransformer transformer)方法的第一个参数，用来控制加入到Viewpager的Views对象是正序的还是倒序的，这里为了实现我们想要的效果，需要让第一个添加到布局的View来到第一个展示，所以传入true；

再细看下我那个自定义的transformer。

**Comment by JJOGGER** [comment]
就算改成false，在第一页下拉的时候position都是固定的1.0，2.0之类的值啊，只有上拉的时候才会变动

**Comment by VDshixiaoming** [comment]
怎么实现循环翻页

**Comment by NateRobinson** [comment]
修改完方向之后，需要在transform里面做些处理，之前的transform就不适合了应该。
