### ISSUE TITLE
大佬 这个可以改造成左右滑动的吗

### ISSUE THREAD

**Issue by anberwei** [NateRobinson/CardStackViewpager#4]

**Comment by NateRobinson** [comment]
理论上是可以的，左右只是变的viewpager的滑动方向，把transformer重新写应该就可以了。

**Comment by anberwei** [comment]
还想保留原有的卡片叠层效果 单纯的改变了滑动方向后 叠层效果没了

**Comment by zouxianbincc** [comment]
@anberwei 你实现了么

**Comment by liuzhenxin2156** [comment]
这个左右怎么滑动啊

**Comment by NateRobinson** [comment]
@liuzhenxin2156 原生的viewpager就是左右滑动的，再参考这个把transformer改一下就可以了。

**Comment by liuzhenxin2156** [comment]
在 VerticalBaseTransformer这个类吗？大佬

**Comment by NateRobinson** [comment]
@liuzhenxin2156 嗯，自己重新写一下这个类，原理应该差不多的，你看看那个readme，原理一样的。

**Comment by liuzhenxin2156** [comment]
@NateRobinson 大佬，我对这个算法。不是很懂，您能具体说下吗？

**Comment by liuzhenxin2156** [comment]
@NateRobinson 大佬，我把这个该我左右滑动就没有下面的叠层效果了。

**Comment by liuzhenxin2156** [comment]
@NateRobinson 这是始末原因啊

**Comment by NateRobinson** [comment]
@liuzhenxin2156 https://github.com/xmuSistone/CardSlidePanel  https://github.com/wenchaojiang/AndroidSwipeableCardStack    你要的是不是这种啊。。。

**Comment by liuzhenxin2156** [comment]
@NateRobinson 不是大佬，我之前就是用这个写的。然后产品又改了。就要这种，我往右滑1到2，然后在往左滑又回到1.你写的这个很符合。但我不能要上下滑动的。要左右滑动的。哎。

**Comment by liuzhenxin2156** [comment]
@NateRobinson大佬 麻烦问下您有思路吗？

**Comment by nickgao1986** [comment]
我往右滑1到2，然后在往左滑又回到1.你写的这个很符合。但我不能要上下滑动的。要左右滑动的。我也特别想要这种，可以重新写一下transformer上传吗

**Comment by nickgao1986** [comment]
已经实现横向滑动并成功应用到项目里，https://github.com/nickgao1986/ViewPaperSwitch

**Comment by nickgao1986** [comment]
> @NateRobinson 不是大佬，我之前就是用这个写的。然后产品又改了。就要这种，我往右滑1到2，然后在往左滑又回到1.你写的这个很符合。但我不能要上下滑动的。要左右滑动的。哎。

已经实现横向滑动并成功应用到项目里，https://github.com/nickgao1986/ViewPaperSwitch
